fix dump with document reference
atn832/cloud_firestore_mocks pull request #133
Opened 2020-10-24 08:41 UTC by technixo

In the previous version. If there contains any DocumentReference fields. call to `instance.dump()` will throw an error `Converting object to an encodable object failed: Instance of 'MockDocumentReference' `

This pull request is fixing it.

2020-10-31 08:52 UTC, atn832 commented
Thanks for contributing a PR. I'll review it tomorrow. In the meantime,  would you mind formatting the code?

https://flutter.dev/docs/development/tools/formatting

2020-10-31 12:32 UTC, technixo commented
We've reformatted the code

2020-11-02 10:38 UTC, atn832 requested changes
Instead of recursively replacing doc.value in `dump`, have you tried modifying `myEncode` to support `MockDocumentReference`? Fixing `myEncode` seems like the proper way to implement this feature. Something like:

```dart
  } else if (item is MockDocumentReference) {
    return "DocumentReference(${item.path})";
  }
```

https://github.com/atn832/cloud_firestore_mocks/blob/e270d9cb0503997f023d3aa078afe599684dce39/lib/src/util.dart#L46

2020-11-02 10:38 UTC, atn832 commented on lib/src/cloud_firestore_mocks_base.dart
> +        propertyValue[i] = deepFixDocumentReferenceProperty(propertyValue[i]);
Looks like `propertyValue` comes from `_docsData`, so this will accidentally overwrite the actual document value.

2020-11-02 10:38 UTC, atn832 commented on lib/src/cloud_firestore_mocks_base.dart
> +        propertyValue[mapProperty.key] =
Same here.

2020-11-02 10:39 UTC, atn832 commented
Thanks for proposing the PR and writing exhaustive tests. Can you try modifying `myEncode` instead? The tests should still work fine after that.

2021-02-25 00:17 UTC, atn832 commented
Feel free to reopen if you plan to fix it.

2021-02-25 00:17 UTC, closed without merging